#!/bin/bash

# Get the current volume level
volume=$(pamixer --get-volume)

# Check if the audio is muted
if pamixer --get-mute | grep -q true; then
    echo "Muted"
else
    echo "Volume: ${volume}%"
fi

# Open pavucontrol on click
if [ "$BLOCK_BUTTON" -eq 1 ]; then
    pavucontrol &
fi