#!/bin/bash

# Get the currently active sink
sink=$(pactl get-default-sink)

# Get the current volume level of the active sink
volume=$(pactl get-sink-volume "$sink" | awk '{print $5}' | tr -d '%')

# Check if the audio is muted
if pactl get-sink-mute "$sink" | grep -q yes; then
    echo ": ${volume}%"
else
    echo ": ${volume}%"
fi

# Open pavucontrol on left click
if [ "$BLOCK_BUTTON" -eq 1 ]; then
    pavucontrol &
fi